ALTER TABLE hosts ALTER COLUMN val_ip_addrs DROP NOT NULL;

ALTER TABLE hosts ADD COLUMN org_id UUID;

ALTER TABLE hosts ADD COLUMN cpu_count BIGINT;

ALTER TABLE hosts ADD COLUMN mem_size BIGINT;

ALTER TABLE hosts ADD COLUMN disk_size BIGINT;

ALTER TABLE hosts ADD COLUMN os TEXT;

ALTER TABLE hosts ADD COLUMN os_version TEXT;