ALTER TABLE hosts ALTER COLUMN val_ip_addrs SET NOT NULL;

ALTER TABLE hosts DROP COLUMN org_id;

ALTER TABLE hosts DROP COLUMN cpu_count;

ALTER TABLE hosts DROP COLUMN mem_size;

ALTER TABLE hosts DROP COLUMN disk_size;

ALTER TABLE hosts DROP COLUMN os;

ALTER TABLE hosts DROP COLUMN os_version;