ALTER TABLE hosts ALTER COLUMN version SET NOT NULL;
ALTER TABLE hosts ALTER COLUMN cpu_count SET NOT NULL;
ALTER TABLE hosts ALTER COLUMN mem_size SET NOT NULL;
ALTER TABLE hosts ALTER COLUMN disk_size SET NOT NULL;
ALTER TABLE hosts ALTER COLUMN os SET NOT NULL;
ALTER TABLE hosts ALTER COLUMN os_version SET NOT NULL;
