name: Docker

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: api

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: |
            nodexeus/bv-api:latest
            nodexeus/bv-api:${{ steps.date.outputs.date }}
          cache-from: type=registry,ref=nodexeus/bv-api:latest
          cache-to: type=inline
