name: Release API

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-**'

permissions:
  contents: write

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get Version
        run: echo GIT_VERSION=$(git describe --tags) >> $GITHUB_ENV

      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
